spring.mail.default-encoding=UTF-8
spring.mailhost=smtp.gmail.com
spring.mail.username=abc
spring.mail.password=password
spring.mail.port=587
spring.mailprotocol=smtp
spring.mail.debug=true
spring.mail.smtp.auth=true
spring.mail.smtp.starttls.enable=true